<a href="https://colab.research.google.com/github/njiutheguru/C_Hangman_Game/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
import seaborn as sns 
#import matplotlib.pylot as plt

In [8]:
#creating a one dimensional array
a1=np.array([1,2,3])
#creating a two dimensional array
a2=np.array([[1,2.0,3.3],
    [4,5,6.5]])
#creating a three dimensional array 

a3=np.array([[[1,2,3],[4,5,6]],
            [[7,8,9],[10,11,12]],
             [[13,14,15],[16,17,18]]])

In [9]:
a1

array([1, 2, 3])

In [10]:
a2


array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [11]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [12]:
a1.shape,a1.ndim,a1.dtype,a1.size,type(a1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [13]:
a2.shape,a2.ndim,a2.dtype,a2.size,type(a2)

((2, 3), 2, dtype('float64'), 6, numpy.ndarray)

In [14]:
a3.shape,a3.ndim,a3.dtype,a3.size,type(a3)

((3, 2, 3), 3, dtype('int64'), 18, numpy.ndarray)

In [27]:
dataf=pd.DataFrame(np.random.randint(10,size=(5,3)),
                   columns=['a','b','c'])
dataf

a  b  c
0  9  1  9
1  3  5  0
2  5  5  2
3  3  1  9
4  2  1  2

In [16]:
#image_path="C:\Users\The Geek Dev\Pictures\Screenshots\Screenshot 2023-05-23 081511.png"
#displaying the image 
#display(Image(filename=image_path))

In [22]:
#/*np.array()
#np.ones()
#np.zeros()
#np.random.rand(5,3)
#np.random.randint(10,size=5)
#np.random.seed() #-pseudo random numbers
#np.unique()*/

In [20]:
zeros=np.zeros((5,3,2))
zeros

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [21]:
ones=np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [28]:
#creating an ara with a range of values 
random_array=np.arange(0,10,2)
random_array

array([0, 2, 4, 6, 8])

In [29]:
#creating an array with an array of floats number 
np.random.random((5,3))

array([[0.25584103, 0.85030194, 0.16428619],
       [0.18205168, 0.72061189, 0.68446626],
       [0.52779054, 0.38169444, 0.36182855],
       [0.33551042, 0.77309972, 0.14692884],
       [0.99020612, 0.75312212, 0.62178581]])

In [63]:
np.random,
#random arry gen
data=np.random.randint(50,100, size=(5,3))
data

array([[88, 74, 54],
       [83, 71, 95],
       [94, 99, 86],
       [78, 84, 92],
       [81, 54, 81]])

In [67]:
np.random.seed(0)
a4=np.random.randint(10,size=(5,3))
a4




array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [66]:
uniquevalues=np.unique(a4)
print(uniquevalues)

[0 1 2 3 4 5 6 7 8 9]


In [68]:
a1

array([1, 2, 3])

In [69]:
ones=np.ones(3)
ones

array([1., 1., 1.])

In [70]:
a1+ones

array([2., 3., 4.])

In [71]:
a1-ones

array([0., 1., 2.])

In [72]:
a1*ones

array([1., 2., 3.])

In [73]:
a1*a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [74]:
a1/2

array([0.5, 1. , 1.5])

In [75]:
a2/a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [76]:
a1/a2


array([[1.        , 1.        , 0.90909091],
       [0.25      , 0.4       , 0.46153846]])

In [78]:
a2//a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [79]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [80]:
a1

array([1, 2, 3])

In [81]:
a2/ones

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [82]:
a1/ones

array([1., 2., 3.])